### ISSUE TITLE
Fix pages not loading on admin site

### ISSUE THREAD

**Issue by Ortovoxx** [ecss-soton/new-web#22]
Searching for pages works but loading pages loads forever.

All pages are accessible however

**Comment by miam-miam100** [comment]
Did you remove the pages that were linked to non-existant user ids?

**Comment by Ortovoxx** [comment]
Pages aren't linked to user ids at all. Regardless all pages are accessible and editable, you just need to search for them. The problem is on https://society.ecs.soton.ac.uk/admin/collections/pages?limit=10

**Comment by miam-miam100** [comment]
Looks like the api doesn't even give you any info
https://society.ecs.soton.ac.uk/api/pages/
compare to 
https://society.ecs.soton.ac.uk/api/sponsors/

**Comment by miam-miam100** [comment]
Same problem with posts. Wiping the collections (including their versions tables) might solve the issue

**Comment by Ortovoxx** [comment]
Yeah noticed the api isn't hydrating the page but not sure as to why. Not a major issue
